GET http://localhost:3000/api/auth/findUsers
###
POST http://localhost:3000/api/auth/local/register
Content-Type: application/json

{
  "email": "thomaslaforge@gmail.com",
  "password": "admin1234"
}

###
POST http://localhost:3000/api/auth/local
Content-Type: application/json

{
  "identifier": "thomaslaforge@gmail.com",
  "password": "admin1234"
} 
