name: back_grenotour

on: # specify the build to trigger the automated ci/cd
  push:
    branches:
      - "main"
      - "develop"
      - "30_asek_creation_du_fichier_yml"

jobs:
  build:
    runs-on : ubuntu-latest

    steps: 

      - name: Checkout repository
        uses: actions/checkout@v2 

      - name: build docker image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN}}
          docker buildx build -t ${{ secrets.DOCKERHUB_USERNAME }}/back_grenotour:latest-${{ github.ref_name }}-${{ runner.os }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/back_grenotour:latest-${{ github.ref_name }}-${{ runner.os }}